name: "cicd"

# When we push the the master branch:
on:
  push:
    branches:
      - cicd

# Here is what we will do
jobs:
  # Deployment:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
      
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Initialize terraform
      working-directory: terraform
      run: terraform init
      
    - name: Plan Terraform
      working-directory: terraform
      run: terraform plan

    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -auto-approve
      
