name: "deploy"

# When we push the the master branch:
on:
  push:
    branches:
      - master

# Here is what we will do
jobs:

  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          # Please refer to: https://github.com/actions/setup-java#supported-distributions
          distribution: 'zulu' #
          java-version: '17'
      
      - name: Download server repo
        run: git submodule update --init --recursive

      - name: Generate Subprojects and Build Paper
        run: |
          cd Paper
          ./gradlew build

      - name: Assemble Paper (paper-api)
        run: cd Paper/paper-api && ./gradlew assemble

      - name: Assemble Paper (paper-mojangapi)
        run: cd Paper/paper-mojangapi && ./gradlew assemble

      - name: Assemble Paper (paper-server)
        run: cd Paper/paper-server && ./gradlew assemble
        
  #terraform:
  #  needs: build-server
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Checkout repo
  #    uses: actions/checkout@v3
  #
  #  - name: Configure AWS credentials
  #    uses: aws-actions/configure-aws-credentials@v2
  #    with:
  #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #      aws-region: eu-west-2
  #
  #  - name: Setup terraform
  #    uses: hashicorp/setup-terraform@v2
  #
  #  - name: Initialize terraform
  #    working-directory: terraform
  #    run: terraform init
      
