name: "deploy"

# When we push the the master branch:
on:
  push:
    branches:
      - master

# Here is what we will do
jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set Git user identity
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          # Please refer to: https://github.com/actions/setup-java#supported-distributions
          distribution: 'zulu' #
          java-version: '17'
      
      - name: Download server repo
        run: git submodule update --init --recursive

      - name: Set up Paper environment
        run: |
          cd Paper
          ./gradlew applyPatches
      
      - name: Build paper
        run: make build-paper
  
  # Deployment:
  terraform:
    needs: build-server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
      
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Initialize terraform
      working-directory: terraform
      run: terraform init
      
    - name: Plan Terraform
      working-directory: terraform
      run: terraform plan

    - name: Apply Terraform
      working-directory: terraform
      run: terraform apply -auto-approve
      
